# Generated by Django 5.2.14 on 2026-05-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configurations',
            },
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean')], default='string', max_length=20, verbose_name='Data Type')),
                ('value', models.TextField(blank=True, verbose_name='Value')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='django_site_settings.settings', verbose_name='Configuration Base')),
            ],
            options={
                'verbose_name': 'Setting Item',
                'verbose_name_plural': 'Setting Items',
                'ordering': ['key'],
            },
        ),
    ]
