# Generated by Django 5.2.14 on 2026-06-04 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title used only within the Django Admin panel.', max_length=255)),
                ('text', models.TextField(help_text='The announcement message body. Supports plain text or raw HTML raw tags.')),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('danger', 'Critical Alert')], default='info', help_text='The visual urgency level of the banner, mapping to bootstrap/tailwind alert classes.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Global visibility toggle for this specific announcement.')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact date and time when the banner should start displaying.')),
                ('end_at', models.DateTimeField(help_text='The exact date and time when the banner should be automatically hidden.')),
                ('priority', models.IntegerField(default=0, help_text='If multiple announcements are active simultaneously, the one with the highest priority displays first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Announcement',
                'verbose_name_plural': 'Site Announcements',
                'db_table': 'site_announcements',
            },
        ),
    ]
