# Generated by Django 5.2.14 on 2026-06-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_site_settings', '0002_siteannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDjangoGroupRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_group_relations', related_query_name='django_group_relation', to='auth.group')),
            ],
            options={
                'verbose_name': 'Setting django group relations',
                'verbose_name_plural': 'Setting django group relation',
                'db_table': 'setting_django_group_relation',
            },
        ),
        migrations.CreateModel(
            name='GroupSettingItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setting_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_item_relations', related_query_name='setting_item_relation', to='django_site_settings.appsetting')),
            ],
            options={
                'verbose_name': 'Setting group item relations',
                'verbose_name_plural': 'Setting group item relation',
                'db_table': 'setting_group_item_relations',
            },
        ),
        migrations.CreateModel(
            name='SettingAccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Group Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_groups', models.ManyToManyField(blank=True, null=True, related_name='setting_access_groups', related_query_name='setting_access_group', through='django_site_settings.GroupDjangoGroupRelation', to='auth.group', verbose_name='Django Groups')),
                ('setting_items', models.ManyToManyField(blank=True, null=True, related_name='setting_access_groups', related_query_name='setting_access_group', through='django_site_settings.GroupSettingItemRelation', to='django_site_settings.appsetting', verbose_name='Setting Items')),
            ],
            options={
                'verbose_name': 'Setting Access Group',
                'verbose_name_plural': 'Setting Access Groups',
                'db_table': 'setting_access_groups',
            },
        ),
        migrations.AddField(
            model_name='groupsettingitemrelation',
            name='access_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_item_relations', related_query_name='setting_item_relation', to='django_site_settings.settingaccessgroup'),
        ),
        migrations.AddField(
            model_name='groupdjangogrouprelation',
            name='access_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_group_relations', related_query_name='django_group_relation', to='django_site_settings.settingaccessgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsettingitemrelation',
            unique_together={('access_group', 'setting_item')},
        ),
        migrations.AlterUniqueTogether(
            name='groupdjangogrouprelation',
            unique_together={('access_group', 'django_group')},
        ),
    ]
