# Generated by Django 5.2.15 on 2026-06-05 10:09

import django_site_settings.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_site_settings', '0003_groupdjangogrouprelation_groupsettingitemrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteannouncement',
            name='text',
            field=django_site_settings.fields.SanitizedHTMLField(help_text='The announcement message body. Supports plain text or raw HTML raw tags.'),
        ),
    ]
